import type { Category, Coupon, Product, StoreState } from './types.js';

export const categories: Category[] = [
  {
    id: 'womens-fashion',
    label: "Woman's Fashion",
    slug: 'womens-fashion',
    icon: 'Dress',
    children: ['Dresses', 'Shoes', 'Bags'],
    sortOrder: 0,
    parentId: null,
  },
  {
    id: 'mens-fashion',
    label: "Men's Fashion",
    slug: 'mens-fashion',
    icon: 'Shirt',
    children: ['Shirts', 'Sneakers', 'Watches'],
    sortOrder: 1,
    parentId: null,
  },
  {
    id: 'electronics',
    label: 'Electronics',
    slug: 'electronics',
    icon: 'Monitor',
    children: [],
    sortOrder: 2,
    parentId: null,
  },
  {
    id: 'home-lifestyle',
    label: 'Home & Lifestyle',
    slug: 'home-lifestyle',
    icon: 'Home',
    children: [],
    sortOrder: 3,
    parentId: null,
  },
  {
    id: 'medicine',
    label: 'Medicine',
    slug: 'medicine',
    icon: 'HeartPulse',
    children: [],
    sortOrder: 4,
    parentId: null,
  },
  {
    id: 'sports-outdoor',
    label: 'Sports & Outdoor',
    slug: 'sports-outdoor',
    icon: 'Dumbbell',
    children: [],
    sortOrder: 5,
    parentId: null,
  },
  {
    id: 'babys-toys',
    label: "Baby's & Toys",
    slug: 'babys-toys',
    icon: 'Gamepad2',
    children: [],
    sortOrder: 6,
    parentId: null,
  },
  {
    id: 'groceries-pets',
    label: 'Groceries & Pets',
    slug: 'groceries-pets',
    icon: 'ShoppingBasket',
    children: [],
    sortOrder: 7,
    parentId: null,
  },
  {
    id: 'health-beauty',
    label: 'Health & Beauty',
    slug: 'health-beauty',
    icon: 'Sparkles',
    children: [],
    sortOrder: 8,
    parentId: null,
  },
];

export const products: Product[] = [
  {
    id: 'havic-gamepad',
    name: 'HAVIT HV-G92 Gamepad',
    category: 'electronics',
    description:
      'PlayStation 5 controller skin with high quality vinyl and air channel adhesive for easy bubble-free install.',
    price: 120,
    originalPrice: 160,
    discountPercent: 40,
    rating: 5,
    reviewCount: 88,
    stockStatus: 'In Stock',
    colors: ['#111111', '#db4444'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: false,
    flags: ['flash', 'related'],
    image: '/assets/products/havit-hv-g92-gamepad.jpg',
  },
  {
    id: 'ak-keyboard',
    name: 'AK-900 Wired Keyboard',
    category: 'electronics',
    description: 'RGB mechanical keyboard with compact layout and responsive switches.',
    price: 960,
    originalPrice: 1160,
    discountPercent: 35,
    rating: 4,
    reviewCount: 75,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: [],
    isNew: false,
    flags: ['flash', 'related'],
    image: '/assets/products/ak-900-keyboard.jpg',
  },
  {
    id: 'ips-monitor',
    name: 'IPS LCD Gaming Monitor',
    category: 'electronics',
    description: 'Wide color display for immersive gaming and crisp productivity.',
    price: 370,
    originalPrice: 400,
    discountPercent: 30,
    rating: 5,
    reviewCount: 99,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: [],
    isNew: false,
    flags: ['flash', 'related', 'best'],
    image: '/assets/products/ips-monitor.jpg',
  },
  {
    id: 'comfort-chair',
    name: 'S-Series Comfort Chair',
    category: 'home-lifestyle',
    description: 'Ergonomic accent chair with soft seat and sculpted shell.',
    price: 375,
    originalPrice: 400,
    discountPercent: 25,
    rating: 4.5,
    reviewCount: 99,
    stockStatus: 'In Stock',
    colors: ['#db4444', '#111111'],
    sizes: [],
    isNew: false,
    flags: ['flash'],
    image: '/assets/products/comfort-chair.jpg',
  },
  {
    id: 'north-coat',
    name: 'The North Coat',
    category: 'mens-fashion',
    description: 'Warm winter coat with tailored profile.',
    price: 260,
    originalPrice: 360,
    discountPercent: 0,
    rating: 5,
    reviewCount: 65,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: false,
    flags: ['best'],
    image: '/assets/products/north-coat.jpg',
  },
  {
    id: 'gucci-bag',
    name: 'Gucci Duffle Bag',
    category: 'womens-fashion',
    description: 'Premium travel duffle with polished hardware.',
    price: 960,
    originalPrice: 1160,
    discountPercent: 0,
    rating: 4.5,
    reviewCount: 65,
    stockStatus: 'In Stock',
    colors: ['#8b5e3c'],
    sizes: [],
    isNew: false,
    flags: ['best'],
    image: '/assets/products/gucci-bag.jpg',
  },
  {
    id: 'rgb-cooler',
    name: 'RGB Liquid CPU Cooler',
    category: 'electronics',
    description: 'Dual fan cooler with vivid RGB lighting.',
    price: 160,
    originalPrice: 170,
    discountPercent: 0,
    rating: 4.5,
    reviewCount: 65,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: [],
    isNew: false,
    flags: ['best', 'related'],
    image: '/assets/products/rgb-cooler.jpg',
  },
  {
    id: 'bookshelf',
    name: 'Small BookShelf',
    category: 'home-lifestyle',
    description: 'Compact shelf for books, decor, and daily essentials.',
    price: 360,
    originalPrice: 0,
    discountPercent: 0,
    rating: 5,
    reviewCount: 65,
    stockStatus: 'In Stock',
    colors: ['#916a49'],
    sizes: [],
    isNew: false,
    flags: ['best'],
    image: '/assets/products/bookshelf.jpg',
  },
  {
    id: 'breed-dog-food',
    name: 'Breed Dry Dog Food',
    category: 'groceries-pets',
    description: 'Nutrient-rich dry dog food for daily feeding.',
    price: 100,
    originalPrice: 0,
    discountPercent: 0,
    rating: 3,
    reviewCount: 35,
    stockStatus: 'In Stock',
    colors: [],
    sizes: [],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/breed-dog-food.jpg',
  },
  {
    id: 'canon-camera',
    name: 'CANON EOS DSLR Camera',
    category: 'electronics',
    description: 'Sharp DSLR camera for creators and everyday moments.',
    price: 360,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4,
    reviewCount: 95,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: [],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/canon-camera.jpg',
  },
  {
    id: 'gaming-laptop',
    name: 'ASUS FHD Gaming Laptop',
    category: 'electronics',
    description: 'Portable gaming laptop with bright display.',
    price: 700,
    originalPrice: 0,
    discountPercent: 0,
    rating: 5,
    reviewCount: 325,
    stockStatus: 'In Stock',
    colors: ['#111111'],
    sizes: [],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/gaming-laptop.jpg',
  },
  {
    id: 'curology-set',
    name: 'Curology Product Set',
    category: 'health-beauty',
    description: 'Daily skincare essentials in a clean shelf-ready set.',
    price: 500,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4,
    reviewCount: 145,
    stockStatus: 'In Stock',
    colors: [],
    sizes: [],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/curology-set.jpg',
  },
  {
    id: 'kids-car',
    name: 'Kids Electric Car',
    category: 'babys-toys',
    description: 'Ride-on electric car with bold red finish.',
    price: 960,
    originalPrice: 0,
    discountPercent: 0,
    rating: 5,
    reviewCount: 65,
    stockStatus: 'In Stock',
    colors: ['#db4444', '#111111'],
    sizes: [],
    isNew: true,
    flags: ['explore'],
    image: '/assets/products/kids-car.jpg',
  },
  {
    id: 'soccer-cleats',
    name: 'Jr. Zoom Soccer Cleats',
    category: 'sports-outdoor',
    description: 'Lightweight cleats for quick cuts and strong grip.',
    price: 1160,
    originalPrice: 0,
    discountPercent: 0,
    rating: 5,
    reviewCount: 35,
    stockStatus: 'In Stock',
    colors: ['#f4ce14', '#db4444'],
    sizes: ['S', 'M', 'L'],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/soccer-cleats.jpg',
  },
  {
    id: 'gamepad-black',
    name: 'GP11 Shooter USB Gamepad',
    category: 'electronics',
    description: 'Classic gamepad for PC and console play.',
    price: 660,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.5,
    reviewCount: 55,
    stockStatus: 'In Stock',
    colors: ['#111111', '#db4444'],
    sizes: [],
    isNew: true,
    flags: ['explore'],
    image: '/assets/products/gamepad-black.jpg',
  },
  {
    id: 'satin-jacket',
    name: 'Quilted Satin Jacket',
    category: 'womens-fashion',
    description: 'Soft satin jacket with quilted texture.',
    price: 660,
    originalPrice: 0,
    discountPercent: 0,
    rating: 4.5,
    reviewCount: 55,
    stockStatus: 'In Stock',
    colors: ['#31563a', '#db4444'],
    sizes: ['S', 'M', 'L'],
    isNew: false,
    flags: ['explore'],
    image: '/assets/products/satin-jacket.jpg',
  },
];

export const coupons: Coupon[] = [
  { code: 'EXCLUSIVE10', type: 'percent', amount: 10, active: true },
  { code: 'SAVE50', type: 'fixed', amount: 50, active: true },
];

export const createInitialStore = (): StoreState => ({
  users: [
    {
      id: 'demo-user',
      firstName: 'Md',
      lastName: 'Rimel',
      email: 'rimel@example.com',
      address: 'Kingston, 5236, United States',
      passwordHash: '$2a$10$B6dNT7Tq7i.FwVT3ZmNFz.j2JcJzTxzsW/qOJcE.FfrzLOq67kd6a',
      role: 'admin',
    },
    {
      id: 'admin-user',
      firstName: 'Admin',
      lastName: 'Operator',
      email: 'admin@exclusive.com',
      address: 'Head Office, 100 Admin Way',
      // Admin123! — bcrypt hash cost 10
      passwordHash: '$2b$10$VCpqK2jMV2ZDhWQTC2OfpO27xvtqeZGZ1oshL8r5lWqlzfBTk9FvC',
      role: 'admin',
    },
  ],
  categories,
  products,
  carts: [
    {
      id: 'demo-cart',
      userId: 'demo-user',
      items: [
        {
          id: 'ci-1',
          productId: 'havic-gamepad',
          quantity: 2,
          selectedColor: '#db4444',
          selectedSize: 'M',
        },
      ],
    },
  ],
  wishlists: [{ userId: 'demo-user', productIds: ['gucci-bag', 'rgb-cooler'] }],
  orders: [],
  coupons,
  contactMessages: [],
});
